#!/bin/bash
 
target=zImage.initrd
ofile=GrImage
KSRC=/home/nold/gclinux/linux-2.6.32
[ -r ${KSRC}/arch/powerpc/boot/${target} ] || {
 echo "Can't find target image ${KSRC}/arch/powerpc/boot/${target}"
 exit 1
}
 
cp ${KSRC}/arch/powerpc/boot/${target} ${ofile}
 
CROSS=powerpc-linux-
 
echo "+ building DOL"
load=$(${CROSS}readelf -l "$ofile" | \
	perl -lane'printf"%08x\n",hex($F[3])+0x80000000 if /LOAD/;')
echo "  LOAD: $load"
entry=$(${CROSS}readelf -l "$ofile" | \
	perl -lane'printf"%08x\n",hex($F[2])+0x80000000 if /Entry point/;')
echo "  EP  : $entry"
 
${CROSS}objcopy -O binary \
	-R .comment -R .shstrtab -R .symtab -R .strtab \
	-R .gnu.attributes \
	${ofile} ${ofile}.bin
doltool -c ${ofile}.bin $load $entry
doltool -i ${ofile}.dol
echo ""

